config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :sessions
  resources :users do
    resources :rsvps
  end
  get '/rsvps/new' => 'rsvps#new', as: :new_rsvp
  get '/rsvps/:id' => 'rsvps#show', as: :rsvp
  resources :comments, only: :index
  resources :foods
  resources :stories, only: :index
  resources :photos, only: :index
  resources :wedding_parties, only: :index
  resources :deets, only: :index
  resources :reservations
  get 'password_resets' => 'password_resets#new'
  put 'password_resets' => 'password_resets#update'
end

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Admin</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Options <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href=<%= new_user_path %>>Users</a></li>
            <li><a href=<%= user_rsvps_path(current_user) %>>RSVPS</a></li>
            <li><a href=<%= foods_path %>>Menu</a></li>
            <li><a href=<%= comments_path %>>Comments</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav><!--/.navbar -->

app/views/shared/_header.html.erb
<header>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Our Story', stories_path %>
  <%= link_to 'RSVP', new_rsvp_path %>
  <%= link_to 'Photos', photos_path %>
  <%= link_to 'Wedding Party', wedding_parties_path %>
  <%= link_to 'The Deets', deets_path %>
  <% if session[:user_id] == nil %>
    <%= link_to 'Login', new_session_path %>
  <% else %>
    <%= link_to 'Logout', "/sessions/#{current_user.id}", method: :delete %>
  <% end %>
</header>
<% if current_user && current_user.admin? %>
  <%= render 'shared/admin_nav' %>
<% end %>