config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :sessions
  resources :users do
    resources :rsvps
  end
  get '/rsvps/new' => 'rsvps#new', as: :new_rsvp
  get '/rsvps/:id' => 'rsvps#show', as: :rsvp
  resources :comments, only: :index
  resources :foods
  resources :stories, only: :index
  resources :photos, only: :index
  resources :wedding_parties, only: :index
  resources :deets, only: :index
  resources :reservations
  get 'password_resets' => 'password_resets#new'
  put 'password_resets' => 'password_resets#update'
end

app/models/rsvp.rb
class Rsvp

  include ActiveModel::Validations
  include ActiveModel::Conversion

  validates :number_of_guests,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: ->(rsvp) { rsvp.user.max_guests },
              message: "Please select a valid number of guests"},
            if: :attending?

  validates :attending, inclusion: {in: [true, false], message: "You must accept or decline"}

  def persisted?
    false
  end

  def initialize(attributes = {})
    @attributes = attributes
  end

  def save_fields
    valid = self.valid?
    if valid
      User.transaction do
        user.update_attributes!(attending: attending,
                                number_of_guests: number_of_guests,
                                food_id: user_food_id, comments: comments)
        if user.attending
          guests.each do |guest|
            Guest.create!(user_id: user.id, name: guest[0], food_id: guest[1])
          end
        end
      end
    end
    valid
  rescue
    false
  end

  def attending?
    attending
  end

  def attending
    if @attributes[:attending].nil?
      nil
    else
      @attributes[:attending] == "true"
    end
  end

  def user
    @attributes[:user] ||= User.find(@attributes[:user_id])
  end

  private
  def guests
    guests = @attributes[:guests].to_a
    guests.reject { |guest| guest[1]['name'].empty? }.map do |guest|
      # guest => ["0", {"name"=>"Bob", "food_id"=>"1"}]
      [guest[1]['name'], guest[1]['food_id']]
    end
    # [[guest_name, guest_food_id], ...]
  end


  def number_of_guests
    @attributes[:number_of_guests]
  end

  def user_food_id
    @attributes[:user_food_id]
  end

  def comments
    @attributes[:comments]
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  before_action :confirm_logged_in


  def index
    @users = User.all
  end

  def new
    @user = User.find current_user.id
    @rsvp = Rsvp.new
    @foods = Food.all
    build_guest_fields
    if !current_user.admin?
      confirm_new_rsvp
    end
  end

  def create
    @rsvp = Rsvp.new(secure_params.merge ({user_id: current_user.id, guests: params[:guest]}))
    if @rsvp.save_fields
      flash[:partial] = current_user.reload.attending ? 'dance' : 'cry'
      redirect_to root_path
    else
      @foods = Food.all
      @user = current_user
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @guests = Guest.where(user_id: params[:id])
  end


  def secure_params
    params.require(:rsvp).permit(:attending, :number_of_guests,
                                 :user_food_id, :comments, :user_id, guest: [:name, :food_id])
  end
end

app/views/rsvps/_rsvp_table.html.erb
<div class=".table-responsive">
  <div class="table-container">
    <div class="table-row">
      <div class="col-md-12">
        <h1 class="text-center">
          RSVP List:
        </h1>
      </div>
      <div id="no-more-tables">
        <table class="col-md-12 table-bordered table-striped table-condensed cf">
          <thead class="cf">
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th class="numeric"># of guests</th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <% if user.attending %>
              <tr>
                <td class="col-md-4" data-title="Name"><%= user.name %></td>
                <td class="col-md-4" data-title="Email"><%= user.email %></td>
                <td class="col-md-2" data-title="Number_of_guests"><%= link_to user.number_of_guests, rsvp_path(user) %></td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/rsvps/_show_rsvp.html.erb
<div class=".table-responsive">
  <div class="table-container">
    <div class="table-row">
      <div class="col-md-12">
        <h1 class="text-center">
          <%= "Guests for #{@user.name}" %>
        </h1>
      </div>
      <div id="no-more-tables">
        <table class="col-md-12 table-bordered table-striped table-condensed cf">
          <thead class="cf">
          <tr>
            <th>Name</th>
            <th>Food Choice</th>
          </tr>
          </thead>
          <tbody>
          <% @guests.each do |guest| %>
            <tr>
              <td data-title="Name"><%= guest.name %></td>
              <td data-title="Guest_food"><%= guest.food.name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/rsvps/index.html.erb
<div class="fullscreen-bg">
  <div id="table-wrapper">
    <%= render 'rsvp_table' %>
  </div>
  <div class="total-guests">
    Total Guests: <%= total_guests %>
  </div>
</div>
<div class="quote-bar">Never love anyone who treats you like you're ordinary ~ Oscar Wilde
</div>

app/views/rsvps/new.html.erb
<div class="page-title">RSVP</div>
<div class="rsvp-container">
  <div class="header">
    <div class="page-title">Evan & Crystal</div>
    <div class="date" id="rsvp">April 5, 2015</div>
    <p>You're invited to come celebrate with us! If you have not done so already, please RSVP
      so that we can accommodate you. </p>
  </div>

  <%= form_for [current_user, @rsvp] do |f| %>
    <div id="attending">
      *Will you be attending?
    </div>

    <div class="error">
      <% if @rsvp.errors.any? %>
        <% @rsvp.errors.each do |_, message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>
    </div>

    <div class="radio">
      <label>
        <%= f.radio_button :attending, true, type: "reset" %>
        Accept with Pleasure
      </label>
    </div>

    <div class="radio">
      <label>
        <%= f.radio_button :attending, false, type: "reset" %>
        Decline with Regret
      </label>
    </div>

    <div class="accept-options">
      <div class="number-of-guests">
        <%= f.label :number_of_guests %>
        <%= f.select :number_of_guests, (0..current_user.max_guests) %>
      </div>

      <div class="user-meal-choice">
        <%= f.label :user_food_id, "Food choice for #{current_user.name}" %>
        <%= f.collection_select(:user_food_id, @foods, :id, :name) %>
      </div>
    </div>

    <div class="guest-options">
      <% @user.guests.each_with_index do |guest, index| %>
        <div class="guest">
          <%= label_tag :guest_name %>
          <%= text_field "guest[#{index}]", :name %>
          <br>
          <%= label_tag :guest_meal_choice %>
          <%= collection_select("guest[#{index}]", :food_id, @foods, :id, :name) %>
        </div>
      <% end %>
      <br>
    </div>
    <div class="comments">
      Comments or Questions?
    </div>
    <%= f.text_area :comments, class: 'form-control' %>
    <div id="submit" class="rsvp-submit">
      <%= f.submit 'Submit' %>
    </div>
  <% end %>
</div>
<div class="quote-bar">After all these years, I see that I was mistaken about Eve in the beginning;
  it is better to live outside the Garden with her than inside it without her.” ~ Mark Twain
</div>

app/views/rsvps/show.html.erb
<div class="fullscreen-bg">
  <div id="table-wrapper">
    <%= render 'show_rsvp' %>
  </div>
</div>
<div class="quote-bar">Never love anyone who treats you like you're ordinary ~ Oscar Wilde
</div>