config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :sessions
  resources :users do
    resources :rsvps
  end
  get '/rsvps/new' => 'rsvps#new', as: :new_rsvp
  get '/rsvps/:id' => 'rsvps#show', as: :rsvp
  resources :comments, only: :index
  resources :foods
  resources :stories, only: :index
  resources :photos, only: :index
  resources :wedding_parties, only: :index
  resources :deets, only: :index
  resources :reservations
  get 'password_resets' => 'password_resets#new'
  put 'password_resets' => 'password_resets#update'
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :description, length:{ maximum:255}
  validates :name, length:{ maximum:255}

  belongs_to :user
  belongs_to :guest
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action do
    confirm_admin
  end

  def index
    @foods =Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(secure_params)
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.destroy(params[:id])
    redirect_to foods_path
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    @food.update(secure_params)
    redirect_to foods_path
  end

  def secure_params
    params.require(:food).permit(:name,:description)
  end
end

app/views/foods/_food_table.html.erb
<div class=".table-responsive">
  <div class="table-container">
    <div class="table-row">
      <div class="col-md-12">
        <h1 class="text-center">
          Menu Items:
        </h1>
      </div>
      <div id="no-more-tables">
        <table class="col-md-12 table-bordered table-striped table-condensed cf">
          <thead class="cf">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td data-title="Name"><%= food.name %></td>
              <td data-title="Description"><%= food.description %></td>
              <td data-title="Edit-food"><%= link_to "Edit #{food.name}", edit_food_path(food) %></td>
              <td data-title="Edit-food"><%= link_to "Delete", food_path(food), method: 'Delete', class: "btn btn-danger btn-mini" %></td>
            </tr>
          <% end %>
          <tr>
          </tr>
          </tbody>
        </table>
        <div class="btn">
          <%= link_to 'Add food item', new_food_path, class: "btn btn-info btn-mini" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="fullscreen-bg">
  <div class="edit-food-container">
    <h1>Edit: <%= @food.name %></h1>
    <%= form_for @food do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: @food.name %>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, placeholder: @food.description, class: 'form-control' %>
      <%= f.submit 'Edit' %>
    <% end %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="fullscreen-bg">
  <div id="table-wrapper">
    <%= render 'food_table' %>
  </div>
</div>
<div class="quote-bar">“We're all a little weird and life's a little weird. And when we find someone who's weirdness is
  compatible with ours, we join up with them and fall in mutual weirdness call it love.” ~ Dr. Suess
</div>

app/views/foods/new.html.erb
<div class="fullscreen-bg">
  <div class="edit-food-container">
    <h1>Add a food item</h1>
    <%= form_for @food do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= f.submit 'Add food' %>
    <% end %>
  </div>
</div>
<div class="quote-bar">“Love is a madness; if thwarted it develops fast." ~ Mark Twain
</div>